(function(a){function b(d){if(c[d])return c[d].exports;var e=c[d]={i:d,l:!1,exports:{}};return a[d].call(e.exports,e,e.exports,b),e.l=!0,e.exports}var c={};return b.m=a,b.c=c,b.d=function(a,c,d){b.o(a,c)||Object.defineProperty(a,c,{configurable:!1,enumerable:!0,get:d})},b.n=function(a){var c=a&&a.__esModule?function(){return a['default']}:function(){return a};return b.d(c,'a',c),c},b.o=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)},b.p='',b(b.s=0)})([function(a,b,c){a.exports=c(1)},function(a,b,c){'use strict';function d(a){const b=Object(f.a)(),c=a.map((a)=>`<li><a href="${a.url}" target="_blank">${a.title}</a></li>`);let d=document.getElementById('add-to-cart-button');d||(d=document.getElementById('buybox-see-all-buying-choices-announce'));const e=d.parentNode.parentNode.parentNode,g=document.createElement('div');g.id='uak-button',g.innerHTML=`
    <span class="a-button a-spacing-small a-button-primary a-button-icon">
      <span class="a-button-inner">
      <i class="a-icon a-icon-1click"></i>
        <span id="submit.add-to-cart-announce" class="a-button-text" aria-hidden="true">${b}</span>
      </span>
    </span>

    <div id="uak-stores-modal">
      <ul>${c.join(' ')}</ul>
    </div>
  `,e.insertBefore(g,null)}Object.defineProperty(b,'__esModule',{value:!0});var e=c(2),f=c(3);window.browser=function(){return window.msBrowser||window.browser||window.chrome}();const g=Array.from(document.querySelectorAll('.content li')),h=g.filter((a)=>a.innerText.includes('ISBN-13'))[0];if(h){const a=h.innerText.split(': ')[1].replace('-','').trim(),b=Object(e.a)(a);d(b),browser.runtime.sendMessage({url:b[0].url})}},function(a,b){'use strict';function c(a){return{ca:[{title:'leslibraires.ca',url:`http://www.leslibraires.ca/recherche/?t=&a=&e=&c=&i=${a}&f=&ip=`}],uk:[{title:'hive.co.uk',url:`http://www.hive.co.uk/Search/Keyword?keyword=${a}`}],fr:[{title:'placedeslibraires.fr',url:`http://www.placedeslibraires.fr/dlivre.php?gencod=${a}&rid=`},{title:'lalibrairie.com',url:`https://www.lalibrairie.com/livres/xxx_0-0000000_${a}.html`},{title:'leslibraires.fr',url:`https://www.leslibraires.fr/livre/${a}`}]}}b.a=function(a){const b=window.location.hostname,d=b.split('.').pop(),e=c(a);return e[d]?e[d]:e.fr}},function(a,b){'use strict';b.a=function(){const a=window.location.hostname;return'www.amazon.com'===a||'www.amazon.ca'===a||'www.amazon.co.uk'===a||'www.amazon.in'===a?'Buy in a bookstore':'www.amazon.com.mx'===a||'www.amazon.es'===a?'Compra en una librer\xEDa':'www.amazon.co.jp'===a?'\u66F8\u5E97\u3067\u8CFC\u5165\u3059\u308B':'www.amazon.it'===a?'Acquista in una libreria':'www.amazon.cn'===a?'\u5728\u4E66\u5E97\u4E70\u4E1C\u897F':'www.amazon.com.br'===a?'Comprar em uma livraria':'www.amazon.de'===a||'www.amazon.au'===a?'Kaufen in einer Buchhandlung':'Acheter en librairie'}}]);