import { Store, Category } from '../stores'
import { amazonDevicesStores } from './_amazon-devices'

export const stores: Store[] = [
  ...amazonDevicesStores,
  {
    title: 'leslibraires.ca',
    url: 'https://www.leslibraires.ca/recherche/?t=&a=&e=&c=&i=%1$s&f=&ip=',
    categories: [Category.ENGLISH_BOOKS, Category.STRIPBOOKS, Category.BOOKS],
  },
  {
    title: 'kobo.com',
    url: 'https://www.kobo.com/ca/en/search?query=%1$s',
    categories: [Category.DIGITAL_TEXT],
  },
  {
    title: 'feedbooks.com',
    url: 'https://www.feedbooks.com/search?lang=en&query=%1$s',
    categories: [Category.DIGITAL_TEXT],
  },
  {
    title: 'ethicalbooksearch.com',
    url: 'https://www.ethicalbooksearch.com/ca?source=amazon-alternatives-extension&query=%1$s',
    categories: [Category.ENGLISH_BOOKS, Category.STRIPBOOKS, Category.BOOKS, Category.DIGITAL_TEXT],
  },
  {
    title: 'bestbuy.ca',
    url: 'https://www.bestbuy.ca/en-ca/search?search=%1$s',
    categories: [
      Category.AUTOMOTIVE,
      Category.ELECTRONICS,
      Category.COMPUTERS,
      Category.PC,
      Category.APPLE_DEVICES,
      Category.APPLIANCES,
      Category.KITCHEN,
      Category.POPULAR,
      Category.DVD,
      Category.VIDEOGAMES,
      Category.CLASSICAL,
      Category.LUGGAGE,
      Category.BEAUTY,
      Category.LUXURY_BEAUTY,
      Category.JEWELRY,
      Category.DIY,
      Category.BABY,
      Category.TOYS,
      Category.OFFICE_PRODUCTS,
      Category.GARDEN,
      Category.PHOTO,
      Category.APPAREL,
      Category.CLOTHING,
    ],
  },
  {
    title: 'newegg.ca',
    url: 'https://www.newegg.ca/p/pl?d=%1$s',
    categories: [
      Category.ELECTRONICS,
      Category.COMPUTERS,
      Category.PC,
      Category.APPLE_DEVICES,
      Category.SOFTWARE,
      Category.DVD,
      Category.TOYS,
      Category.VIDEOGAMES,
      Category.SOFTWARE,
      Category.APPLIANCES,
      Category.KITCHEN,
      Category.SHOES,
      Category.DIY,
      Category.FASHION,
      Category.LUGGAGE,
      Category.WATCHES,
      Category.GARDEN,
      Category.PHOTO,
      Category.APPAREL,
      Category.CLOTHING,
    ],
  },
  {
    title: 'pc-canada.com',
    url: 'https://www.pc-canada.com/p/go/go.asp?SearchString=%1$s',
    categories: [
      Category.ELECTRONICS,
      Category.COMPUTERS,
      Category.PC,
      Category.APPLE_DEVICES,
      Category.SOFTWARE,
      Category.DVD,
      Category.VIDEOGAMES,
      Category.SOFTWARE,
      Category.PHOTO,
    ],
  },
]
