import { Category, Store } from '../stores'
import { amazonDevicesStores } from './_amazon-devices'

export const stores: Store[] = [
  ...amazonDevicesStores,
  {
    title: 'genialokal.de',
    url: 'https://www.genialokal.de/Suche/?q=%1$s',
    categories: [Category.BOOKS_INTL_DE, Category.BOOKS_CATALOG],
  },
  {
    title: 'buchhandel.de',
    url: 'https://www.buchhandel.de/suche/ergebnisse?query=%1$s',
    categories: [Category.BOOKS_INTL_DE, Category.BOOKS_CATALOG],
  },
  {
    title: 'buchkatalog.at',
    url: 'https://shop.buchkatalog.at/servlet/SearchDisplay?catalogId=10002&searchTerm=%1$s',
    categories: [Category.BOOKS_INTL_DE, Category.BOOKS_CATALOG],
  },
  {
    title: 'kobo.com',
    url: 'https://www.kobo.com/de/de/search?query=%1$s',
    categories: [Category.DIGITAL_TEXT],
  },
  {
    title: 'feedbooks.com',
    url: 'https://www.feedbooks.com/search?lang=de&query=%1$s',
    categories: [Category.DIGITAL_TEXT],
  },
  {
    title: 'ethicalbooksearch.com',
    url: 'https://www.ethicalbooksearch.com/de?source=amazon-alternatives-extension&query=%1$s',
    categories: [
      Category.ENGLISH_BOOKS,
      Category.STRIPBOOKS,
      Category.BOOKS,
      Category.DIGITAL_TEXT,
      Category.BOOKS_INTL_DE,
      Category.BOOKS_CATALOG,
    ],
  },
  {
    title: 'Thalia',
    url: 'https://www.thalia.de/suche?sq=%1$s',
    categories: [
      Category.ENGLISH_BOOKS,
      Category.STRIPBOOKS,
      Category.BOOKS,
      Category.DIGITAL_TEXT,
      Category.DVD,
      Category.VIDEOGAMES,
      Category.CLASSICAL,
    ],
  },
  {
    title: 'Weltbild',
    url: 'https://www.weltbild.de/suche/%1$s',
    categories: [
      Category.ENGLISH_BOOKS,
      Category.STRIPBOOKS,
      Category.BOOKS,
      Category.DIGITAL_TEXT,
      Category.DVD,
      Category.CLASSICAL,
    ],
  },
  {
    title: 'Hugendubel',
    url: 'https://www.hugendubel.de/de/quickSearch?searchString=%1$s',
    categories: [
      Category.ENGLISH_BOOKS,
      Category.STRIPBOOKS,
      Category.BOOKS,
      Category.DIGITAL_TEXT,
      Category.DVD,
      Category.CLASSICAL,
    ],
  },
  {
    title: 'Mediamarkt',
    url: 'https://www.mediamarkt.de/de/search.html?query=%1$s',
    categories: [
      Category.ENGLISH_BOOKS,
      Category.STRIPBOOKS,
      Category.BOOKS,
      Category.DIGITAL_TEXT,
      Category.DVD,
      Category.CLASSICAL,
      Category.ELECTRONICS,
      Category.COMPUTERS,
      Category.PC,
      Category.APPLIANCES,
      Category.APPLE_DEVICES,
    ],
  },
  {
    title: 'Saturn',
    url: 'https://www.saturn.de/de/search.html?query=%1$s',
    categories: [
      Category.ENGLISH_BOOKS,
      Category.STRIPBOOKS,
      Category.BOOKS,
      Category.DIGITAL_TEXT,
      Category.DVD,
      Category.CLASSICAL,
      Category.ELECTRONICS,
      Category.COMPUTERS,
      Category.PC,
      Category.APPLIANCES,
      Category.APPLE_DEVICES,
    ],
  },
  {
    title: 'Thomann',
    url: 'https://www.thomann.de/intl/search_dir.html?sw=%1$s',
    categories: [Category.CLASSICAL, Category.COMPUTERS, Category.PC, Category.ELECTRONICS, Category.MI],
  },
  {
    title: 'Notebooksbilliger',
    url: 'https://www.notebooksbilliger.de/produkte/%1$s',
    categories: [Category.ELECTRONICS, Category.COMPUTERS],
  },
  {
    title: 'Cyberport',
    url: 'https://www.cyberport.de/tools/search-results.html?q=%1$s',
    categories: [Category.ELECTRONICS, Category.COMPUTERS],
  },
  {
    title: 'Expert',
    url: 'https://www.expert.de/suche?q=%1$s',
    categories: [
      Category.ENGLISH_BOOKS,
      Category.STRIPBOOKS,
      Category.BOOKS,
      Category.DIGITAL_TEXT,
      Category.DVD,
      Category.CLASSICAL,
      Category.ELECTRONICS,
      Category.COMPUTERS,
      Category.PC,
      Category.APPLIANCES,
      Category.APPLE_DEVICES,
    ],
  },
  {
    title: 'Conrad',
    url: 'https://www.conrad.de/de/search.html?search=%1$s',
    categories: [
      Category.ENGLISH_BOOKS,
      Category.STRIPBOOKS,
      Category.BOOKS,
      Category.DIGITAL_TEXT,
      Category.DVD,
      Category.CLASSICAL,
      Category.ELECTRONICS,
      Category.COMPUTERS,
      Category.PC,
      Category.APPLIANCES,
      Category.APPLE_DEVICES,
    ],
  },
]
