import { Category, Store } from '../stores'

export const stores: Store[] = [
  {
    title: 'fnac.com',
    url: 'https://www.fnac.com/SearchResult/ResultList.aspx?Search=%1$s',
    categories: [
      Category.AUTOMOTIVE,
      Category.ELECTRONICS,
      Category.COMPUTERS,
      Category.APPLIANCES,
      Category.KITCHEN,
      Category.POPULAR,
      Category.DVD,
      Category.VIDEOGAMES,
      Category.CLASSICAL,
      Category.LUGGAGE,
      Category.DIY,
      Category.TOYS,
      Category.OFFICE_PRODUCTS,
    ],
  },
  {
    title: 'ldlc.com',
    url: 'https://www.ldlc.com/recherche/%1$s/',
    categories: [Category.ELECTRONICS, Category.COMPUTERS],
  },
  {
    title: 'materiel.net',
    url: 'https://www.materiel.net/recherche/%1$s/',
    categories: [Category.ELECTRONICS, Category.COMPUTERS],
  },
  {
    title: 'topachat.com',
    url: 'https://www.topachat.com/pages/recherche.php?cat=accueil&etou=0&mc=$1%s',
    categories: [Category.ELECTRONICS, Category.COMPUTERS],
  },
  {
    title: 'boulanger.com',
    url: 'https://www.boulanger.com/resultats?tr=%1$s',
    categories: [Category.ELECTRONICS, Category.COMPUTERS, Category.APPLIANCES, Category.KITCHEN],
  },
  {
    title: 'but.fr',
    url: 'https://www.but.fr/Common/Search/SearchProductsList?KeyWords=%1$s',
    categories: [Category.ELECTRONICS, Category.COMPUTERS, Category.APPLIANCES, Category.KITCHEN],
  },
  {
    title: 'backmarket.fr',
    url: 'https://www.backmarket.fr/search/?q=%1$s&ga_search=%1$s#?q=%1$s',
    categories: [Category.ELECTRONICS, Category.COMPUTERS],
  },
  {
    title: 'cdiscount.com',
    url: 'https://www.cdiscount.com/search/10/%1$s.html',
    categories: [
      Category.AUTOMOTIVE,
      Category.ELECTRONICS,
      Category.COMPUTERS,
      Category.APPLIANCES,
      Category.KITCHEN,
      Category.POPULAR,
      Category.DVD,
      Category.VIDEOGAMES,
      Category.CLASSICAL,
      Category.LUGGAGE,
      Category.BEAUTY,
      Category.LUXURY_BEAUTY,
      Category.JEWELRY,
      Category.DIY,
      Category.BABY,
      Category.TOYS,
      Category.OFFICE_PRODUCTS,
    ],
  },
  {
    title: 'rueducommerce.fr',
    url: 'https://www.rueducommerce.fr/recherche/%1$s',
    categories: [
      Category.AUTOMOTIVE,
      Category.ELECTRONICS,
      Category.COMPUTERS,
      Category.APPLIANCES,
      Category.KITCHEN,
      Category.POPULAR,
      Category.DVD,
      Category.VIDEOGAMES,
      Category.CLASSICAL,
      Category.LUGGAGE,
      Category.BEAUTY,
      Category.LUXURY_BEAUTY,
      Category.JEWELRY,
      Category.DIY,
      Category.BABY,
      Category.TOYS,
      Category.OFFICE_PRODUCTS,
    ],
  },
  {
    title: 'rakuten.com',
    url: 'https://fr.shopping.rakuten.com/s/%1$s',
    categories: [
      Category.AUTOMOTIVE,
      Category.ELECTRONICS,
      Category.COMPUTERS,
      Category.APPLIANCES,
      Category.KITCHEN,
      Category.POPULAR,
      Category.DVD,
      Category.VIDEOGAMES,
      Category.CLASSICAL,
      Category.LUGGAGE,
      Category.BEAUTY,
      Category.LUXURY_BEAUTY,
      Category.JEWELRY,
      Category.DIY,
      Category.BABY,
      Category.TOYS,
      Category.OFFICE_PRODUCTS,
    ],
  },
  {
    title: 'culture.leclerc',
    url: 'https://www.culture.leclerc/pageRecherche?q=%1$s&univers=al',
    categories: [
      Category.ENGLISH_BOOKS,
      Category.STRIPBOOKS,
      Category.BOOKS,
      Category.POPULAR,
      Category.DVD,
      Category.VIDEOGAMES,
      Category.CLASSICAL,
    ],
  },
  {
    title: 'placedeslibraires.fr',
    url: 'http://www.placedeslibraires.fr/dlivre.php?gencod=%1$s&rid=',
    categories: [Category.ENGLISH_BOOKS, Category.STRIPBOOKS, Category.BOOKS],
  },
  {
    title: 'lalibrairie.com',
    url: 'https://www.lalibrairie.com/livres/xxx_0-0000000_%1$s.html',
    categories: [Category.ENGLISH_BOOKS, Category.STRIPBOOKS, Category.BOOKS],
  },
  {
    title: 'leslibraires.fr',
    url: 'https://www.leslibraires.fr/livre/%1$s',
    categories: [Category.ENGLISH_BOOKS, Category.STRIPBOOKS, Category.BOOKS],
  },
  {
    title: 'recyclivre.com',
    url: 'https://www.recyclivre.com/shop/recherche?orderby=price&orderway=asc&s=%1$s&submit_search=',
    categories: [Category.ENGLISH_BOOKS, Category.STRIPBOOKS, Category.BOOKS],
  },
  {
    title: 'librairiesindependantes.com',
    url: 'https://www.librairiesindependantes.com/product/%1$s/',
    categories: [Category.ENGLISH_BOOKS, Category.STRIPBOOKS, Category.BOOKS],
  },
  {
    title: 'chapitre.com',
    url: 'https://www.chapitre.com/search/Default.aspx?quicksearch=%1$s',
    categories: [Category.ENGLISH_BOOKS, Category.STRIPBOOKS, Category.BOOKS],
  },
  {
    title: 'bdfugue.com',
    url: 'https://www.bdfugue.com/catalogsearch/result/?q=%1$s',
    categories: [Category.BOOKS, Category.STRIPBOOKS],
  },
  {
    title: 'kobo.com',
    url: 'https://www.kobo.com/fr/fr/search?query=%1$s',
    categories: [Category.DIGITAL_TEXT],
  },
  {
    title: 'emaginaire.com',
    url:
      'https://www.emaginaire.com/listeliv.php?form_recherche_avancee=ok&getbase=ebook&base=ebook&titre=%1$s&titre1=%1$s',
    categories: [Category.DIGITAL_TEXT],
  },
  {
    title: '7switch.com',
    url: 'https://www.7switch.com/fr/list/search/page/1/revelance?q=%1$s',
    categories: [Category.DIGITAL_TEXT],
  },
  {
    title: 'feedbooks.com',
    url: 'http://www.feedbooks.com/search?lang=fr&query=%1$s',
    categories: [Category.DIGITAL_TEXT],
  },
  {
    title: 'numilog.com',
    url: 'https://www.numilog.com/Pages/Recherche/ResultatRecherche.aspx?mode=brSimple&query=%1$s',
    categories: [Category.DIGITAL_TEXT],
  },
  {
    title: 'zalando.fr',
    url: 'https://www.zalando.fr/catalogue/?q=%1$s',
    categories: [Category.SHOES, Category.FASHION, Category.WATCHES, Category.CLOTHING],
  },
  {
    title: 'asos.fr',
    url: 'https://www.asos.com/fr/search/?q=%1$s',
    categories: [Category.SHOES, Category.FASHION, Category.WATCHES, Category.CLOTHING],
  },
  {
    title: 'spartoo.com',
    url: 'https://www.spartoo.com/search.php?keywords=%1$s',
    categories: [Category.SHOES, Category.FASHION, Category.WATCHES, Category.CLOTHING],
  },
  {
    title: 'laredoute.fr',
    url: 'https://www.laredoute.fr/psrch/psrch.aspx?kwrd=%1$s&virtualsite=100#srt=noSorting',
    categories: [
      Category.SHOES,
      Category.FASHION,
      Category.WATCHES,
      Category.CLOTHING,
      Category.ELECTRONICS,
      Category.COMPUTERS,
      Category.APPLIANCES,
      Category.KITCHEN,
      Category.POPULAR,
      Category.DVD,
      Category.VIDEOGAMES,
      Category.CLASSICAL,
      Category.GARDEN,
      Category.LUGGAGE,
      Category.LIGHTING,
    ],
  },
  {
    title: 'philibertnet.com',
    url: 'https://www.philibertnet.com/fr/recherche?controller=search&orderby=position&orderway=desc&search_query=%1$s',
    categories: [Category.TOYS],
  },
  {
    title: 'magicbazar.fr',
    url: 'https://www.magicbazar.fr/recherche/result.php?s=%1$s',
    categories: [Category.TOYS],
  },
  {
    title: 'cobra.fr',
    url: 'https://www.cobra.fr/recherche/%1$s',
    categories: [Category.ELECTRONICS, Category.MI],
  },
  {
    title: 'son-video.com',
    url: 'https://www.son-video.com/recherche?termes=%1$s',
    categories: [Category.ELECTRONICS, Category.MI],
  },
  {
    title: 'woodbrass.com',
    url: 'https://www.woodbrass.com/advanced_search_result.php?keywords=%1$s',
    categories: [Category.ELECTRONICS, Category.MI],
  },
  {
    title: 'manomano.fr',
    url: 'https://www.manomano.fr/recherche/%1$s',
    categories: [Category.DIY, Category.GARDEN],
  },
  {
    title: 'leroymerlin.fr',
    url: 'https://www.leroymerlin.fr/v3/search/search.do?keyword=%1$s',
    categories: [Category.DIY, Category.GARDEN],
  },
  {
    title: 'bricodepot.fr',
    url: 'https://www.bricodepot.fr/catalogue/search/node?query=%1$s',
    categories: [Category.DIY, Category.GARDEN],
  },
  {
    title: 'mr-bricolage.fr',
    url: 'https://www.mr-bricolage.fr/Montauban/catalogsearch/result/?q=%1$s',
    categories: [Category.DIY, Category.GARDEN],
  },
  {
    title: 'castorama.fr',
    url: 'https://www.castorama.fr/search?Ntt=%1$s',
    categories: [Category.DIY, Category.GARDEN],
  },
  {
    title: 'bricorama.fr',
    url: 'https://www.bricorama.fr/catalogsearch/result/?q=%1$s',
    categories: [Category.DIY, Category.GARDEN],
  },
  {
    title: 'bricomarche.fr',
    url: 'https://www.bricomarche.com/search?text=%1$s',
    categories: [Category.DIY, Category.GARDEN],
  },
  {
    title: 'oogarden.com',
    url: 'https://www.oogarden.com/Product/Search?Keyword=%1$s',
    categories: [Category.GARDEN, Category.PETS],
  },
  {
    title: 'santediscount.com',
    url: 'https://www.santediscount.com/catalogsearch/result/?q=%1$s',
    categories: [Category.HPC, Category.BEAUTY, Category.BABY],
  },
  {
    title: 'lasante.net',
    url: 'https://lasante.net/recherche-%1$s',
    categories: [Category.HPC, Category.BEAUTY, Category.BABY],
  },
  {
    title: '1001pharmacies.com',
    url: 'https://www.1001pharmacies.com/search?q=%1$s',
    categories: [Category.HPC, Category.BEAUTY, Category.BABY],
  },
  {
    title: 'pharma-gdd.com',
    url: 'https://www.pharma-gdd.com/fr/search?q=%1$s',
    categories: [Category.HPC, Category.BEAUTY, Category.BABY],
  },
  {
    title: 'doctipharma.fr',
    url: 'https://www.doctipharma.fr/fr/search?q=%1$s',
    categories: [Category.HPC, Category.BEAUTY, Category.BABY],
  },
]
