import { Store } from '../stores'

export default <Store>{
  'pets': [],
  'mobile-apps': [],
  'automotive': [],
  'luggage': [],
  'beauty': [],
  'luxury-beauty': [],
  'jewelry': [],
  'gift-cards': [],
  'digital-text': [],
  'diy': [],
  'baby': [],
  'shoes': [],
  'kitchen': [],
  'dvd': [],
  'grocery': [],
  'office-products': [],
  'appliances': [],
  'handmade': [],
  'electronics': [],
  'hpc': [],
  'computers': [],
  'mi': [],
  'garden': [],
  'toys': [],
  'videogames': [],
  'english-books': [
    {
      title: 'hive.co.uk',
      url: `http://www.hive.co.uk/Search/Keyword?keyword=%1$s`,
    },
  ],
  'stripbooks': [
    {
      title: 'hive.co.uk',
      url: `http://www.hive.co.uk/Search/Keyword?keyword=%1$s`,
    },
  ],
  'books': [
    {
      title: 'hive.co.uk',
      url: `http://www.hive.co.uk/Search/Keyword?keyword=%1$s`,
    },
  ],
  'software': [],
  'lighting': [],
  'fashion': [],
  'under-ten-dollars': [],
  'watches': [],
  'popular': [],
  'classical': [],
  'instant-video': [],
  'industrial': [],
  'sports': [],
  'digital-music': [],
  'clothing': [],
}
